// AUTO-GENERATED by supaflow-platform TypescriptExporter.java
// DO NOT EDIT this file manually. Changes will be overwritten on next platform build.

export type AccessLevel = "editor" | "owner" | "viewer";
export const AccessLevelValues: AccessLevel[] = ["editor", "owner", "viewer"];

export type ArtifactCategory = "ERROR";
export const ArtifactCategoryValues: ArtifactCategory[] = ["ERROR"];

export type CanonicalType = "JSON" | "STRING" | "DOUBLE" | "FLOAT" | "BIGDECIMAL" | "LONG" | "INT" | "SHORT" | "BOOLEAN" | "INSTANT" | "LOCALDATETIME" | "LOCALDATE" | "BINARY" | "XML";
export const CanonicalTypeValues: CanonicalType[] = ["JSON", "STRING", "DOUBLE", "FLOAT", "BIGDECIMAL", "LONG", "INT", "SHORT", "BOOLEAN", "INSTANT", "LOCALDATETIME", "LOCALDATE", "BINARY", "XML"];

export type ChecksumValidationLevel = "NONE" | "ROW_COUNT" | "COLUMN_STATISTICS" | "FULL_INTEGRITY";
export const ChecksumValidationLevelValues: ChecksumValidationLevel[] = ["NONE", "ROW_COUNT", "COLUMN_STATISTICS", "FULL_INTEGRITY"];

export type CloudProvider = "aws" | "gcp" | "azure" | "snowflake" | "pc";
export const CloudProviderValues: CloudProvider[] = ["aws", "gcp", "azure", "snowflake", "pc"];

export type ConnectivityStatus = "DISCONNECTED" | "CONNECTING" | "CONNECTED" | "IDLE" | "STALE" | "LOST";
export const ConnectivityStatusValues: ConnectivityStatus[] = ["DISCONNECTED", "CONNECTING", "CONNECTED", "IDLE", "STALE", "LOST"];

export type ConnectorCapabilities = "REPLICATION_SOURCE" | "REPLICATION_DESTINATION" | "DBT_DATASOURCE" | "REVERSE_ETL_SOURCE" | "REVERSE_ETL_DESTINATION" | "SQL_SCRIPT_EXECUTION";
export const ConnectorCapabilitiesValues: ConnectorCapabilities[] = ["REPLICATION_SOURCE", "REPLICATION_DESTINATION", "DBT_DATASOURCE", "REVERSE_ETL_SOURCE", "REVERSE_ETL_DESTINATION", "SQL_SCRIPT_EXECUTION"];

export type ConnectorType = "SOURCE" | "DESTINATION" | "SOURCE_AND_DESTINATION" | "WAREHOUSE" | "DATABASE" | "API" | "FILE_STORAGE" | "STREAMING" | "CUSTOM";
export const ConnectorTypeValues: ConnectorType[] = ["SOURCE", "DESTINATION", "SOURCE_AND_DESTINATION", "WAREHOUSE", "DATABASE", "API", "FILE_STORAGE", "STREAMING", "CUSTOM"];

export type CredentialType = "git";
export const CredentialTypeValues: CredentialType[] = ["git"];

export type DeploymentService = "ecs" | "ec2" | "eks" | "gke" | "gce" | "aks" | "aci" | "scs" | "docker" | "k8s" | "bare_metal";
export const DeploymentServiceValues: DeploymentService[] = ["ecs", "ec2", "eks", "gke", "gce", "aks", "aci", "scs", "docker", "k8s", "bare_metal"];

export type DestinationTableHandling = "MERGE" | "FAIL" | "DROP";
export const DestinationTableHandlingValues: DestinationTableHandling[] = ["MERGE", "FAIL", "DROP"];

export type EntityType = "project" | "datasource" | "pipeline" | "agent" | "task";
export const EntityTypeValues: EntityType[] = ["project", "datasource", "pipeline", "agent", "task"];

export type Environment = "DEV" | "TEST" | "STAGE" | "UAT" | "PROD";
export const EnvironmentValues: Environment[] = ["DEV", "TEST", "STAGE", "UAT", "PROD"];

export type ErrorHandling = "STRICT" | "MODERATE";
export const ErrorHandlingValues: ErrorHandling[] = ["STRICT", "MODERATE"];

export type FullResyncFrequency = "NEVER" | "DAILY" | "WEEKLY" | "MONTHLY";
export const FullResyncFrequencyValues: FullResyncFrequency[] = ["NEVER", "DAILY", "WEEKLY", "MONTHLY"];

export type FullSyncFrequency = "NEVER" | "DAILY" | "WEEKLY" | "MONTHLY" | "EVERY_RUN";
export const FullSyncFrequencyValues: FullSyncFrequency[] = ["NEVER", "DAILY", "WEEKLY", "MONTHLY", "EVERY_RUN"];

export type IdentifierQuotePreference = "QUOTE_ALWAYS" | "QUOTE_NEVER" | "QUOTE_IF_NEEDED";
export const IdentifierQuotePreferenceValues: IdentifierQuotePreference[] = ["QUOTE_ALWAYS", "QUOTE_NEVER", "QUOTE_IF_NEEDED"];

export type IdentityStrategy = "SOURCE_KEY" | "ROW_HASH" | "NONE";
export const IdentityStrategyValues: IdentityStrategy[] = ["SOURCE_KEY", "ROW_HASH", "NONE"];

export type IncrementalStrategy = "UNSUPPORTED" | "COLUMN_CURSOR" | "CONNECTOR_MANAGED" | "NONE";
export const IncrementalStrategyValues: IncrementalStrategy[] = ["UNSUPPORTED", "COLUMN_CURSOR", "CONNECTOR_MANAGED", "NONE"];

export type IngestionMode = "INCREMENTAL" | "HISTORICAL_PLUS_INCREMENTAL" | "HISTORICAL";
export const IngestionModeValues: IngestionMode[] = ["INCREMENTAL", "HISTORICAL_PLUS_INCREMENTAL", "HISTORICAL"];

export type JobStatus = "queued" | "picked" | "running" | "completed" | "completed_with_warning" | "failed" | "cancelled" | "timed_out" | "skipped" | "nil";
export const JobStatusValues: JobStatus[] = ["queued", "picked", "running", "completed", "completed_with_warning", "failed", "cancelled", "timed_out", "skipped", "nil"];

export type JobType = "project" | "datasource" | "datasource_test" | "datasource_schema_refresh" | "datasource_reencrypt" | "pipeline_run" | "dbt_command" | "git_command" | "agent_command" | "task_run";
export const JobTypeValues: JobType[] = ["project", "datasource", "datasource_test", "datasource_schema_refresh", "datasource_reencrypt", "pipeline_run", "dbt_command", "git_command", "agent_command", "task_run"];

export type LifecycleStatus = "REGISTERED" | "PENDING_APPROVAL" | "APPROVED" | "ACTIVE" | "SUSPENDED" | "TERMINATED";
export const LifecycleStatusValues: LifecycleStatus[] = ["REGISTERED", "PENDING_APPROVAL", "APPROVED", "ACTIVE", "SUSPENDED", "TERMINATED"];

export type LoadMode = "APPEND" | "MERGE" | "TRUNCATE_AND_LOAD" | "OVERWRITE";
export const LoadModeValues: LoadMode[] = ["APPEND", "MERGE", "TRUNCATE_AND_LOAD", "OVERWRITE"];

export type LoadOptimizationMode = "LATENCY" | "COST" | "ADAPTIVE";
export const LoadOptimizationModeValues: LoadOptimizationMode[] = ["LATENCY", "COST", "ADAPTIVE"];

export type MetadataSkipReason = "MISSING_CURSOR" | "SCHEMA_EVOLUTION_MODE_BLOCK_ALL" | "SCHEMA_EVOLUTION_MODE_COLUMN_LEVEL_ONLY" | "BREAKING_TYPE_CHANGE" | "UNSUPPORTED_TYPE" | "MISSING_PRIMARY_KEY" | "DELETED_FROM_SOURCE" | "CHANGE_TRACKING_NOT_ENABLED";
export const MetadataSkipReasonValues: MetadataSkipReason[] = ["MISSING_CURSOR", "SCHEMA_EVOLUTION_MODE_BLOCK_ALL", "SCHEMA_EVOLUTION_MODE_COLUMN_LEVEL_ONLY", "BREAKING_TYPE_CHANGE", "UNSUPPORTED_TYPE", "MISSING_PRIMARY_KEY", "DELETED_FROM_SOURCE", "CHANGE_TRACKING_NOT_ENABLED"];

export type NamespaceRulesEnum = "MIRROR_SOURCE" | "DESTINATION_DEFINED" | "FIVETRAN_NAMING";
export const NamespaceRulesEnumValues: NamespaceRulesEnum[] = ["MIRROR_SOURCE", "DESTINATION_DEFINED", "FIVETRAN_NAMING"];

export type ObjectType = "PRIMARY" | "ASSOCIATION" | "HISTORY" | "METADATA";
export const ObjectTypeValues: ObjectType[] = ["PRIMARY", "ASSOCIATION", "HISTORY", "METADATA"];

export type PipelineType = "REPLICATION" | "ACTIVATION";
export const PipelineTypeValues: PipelineType[] = ["REPLICATION", "ACTIVATION"];

export type ProgressType = "step_based" | "percentage_based" | "count_based" | "indeterminate";
export const ProgressTypeValues: ProgressType[] = ["step_based", "percentage_based", "count_based", "indeterminate"];

export type ProjectType = "INGESTION" | "TRANSFORMATION" | "ACTIVATION";
export const ProjectTypeValues: ProjectType[] = ["INGESTION", "TRANSFORMATION", "ACTIVATION"];

export type Region = "ap_southeast_1" | "us_west_1" | "eu_central_1";
export const RegionValues: Region[] = ["ap_southeast_1", "us_west_1", "eu_central_1"];

export type ReleaseStage = "SOON" | "BRONZE" | "SILVER" | "GOLD" | "CERTIFIED";
export const ReleaseStageValues: ReleaseStage[] = ["SOON", "BRONZE", "SILVER", "GOLD", "CERTIFIED"];

export type Role = "admin" | "member" | "supa_agent_role";
export const RoleValues: Role[] = ["admin", "member", "supa_agent_role"];

export type ScheduleExecutionStatus = "PENDING" | "RUNNING" | "COMPLETED" | "COMPLETED_WITH_WARNING" | "FAILED" | "CANCELLED" | "SKIPPED" | "TIMED_OUT";
export const ScheduleExecutionStatusValues: ScheduleExecutionStatus[] = ["PENDING", "RUNNING", "COMPLETED", "COMPLETED_WITH_WARNING", "FAILED", "CANCELLED", "SKIPPED", "TIMED_OUT"];

export type SchemaEvolutionMode = "ALLOW_ALL" | "BLOCK_ALL" | "COLUMN_LEVEL_ONLY";
export const SchemaEvolutionModeValues: SchemaEvolutionMode[] = ["ALLOW_ALL", "BLOCK_ALL", "COLUMN_LEVEL_ONLY"];

export type SelectionOrigin = "explicit" | "schema_evolution";
export const SelectionOriginValues: SelectionOrigin[] = ["explicit", "schema_evolution"];

export type State = "active" | "inactive" | "deleted" | "draft" | "failed" | "provisioning" | "locked";
export const StateValues: State[] = ["active", "inactive", "deleted", "draft", "failed", "provisioning", "locked"];

export type TaskType = "sql_script" | "snowflake_dbt" | "dbt_cloud" | "lambda" | "airflow";
export const TaskTypeValues: TaskType[] = ["sql_script", "snowflake_dbt", "dbt_cloud", "lambda", "airflow"];

export type TenantType = "TRIAL" | "PAID" | "INTERNAL" | "PARTNER";
export const TenantTypeValues: TenantType[] = ["TRIAL", "PAID", "INTERNAL", "PARTNER"];

export type VersionAvailability = "GLOBAL" | "INTERNAL" | "PARTNER" | "TENANT_SPECIFIC";
export const VersionAvailabilityValues: VersionAvailability[] = ["GLOBAL", "INTERNAL", "PARTNER", "TENANT_SPECIFIC"];

export interface ActiveSchedules {
  created_at: string;
  cron_schedule: string;
  description: string | null;
  entries: any;
  entry_count: number;
  failure_count: number | null;
  last_execution_at: string | null;
  last_run_at: string | null;
  last_status: ScheduleExecutionStatus | null;
  next_run_at: string | null;
  schedule_id: string;
  schedule_name: string;
  success_count: number | null;
  timezone: string;
  updated_at: string;
  workspace_id: string;
  workspace_name: string;
}

export interface AgentBillingSummary {
  active_minutes: number;
  active_sessions: number;
  billing_date: string;
  closed_minutes: number;
  closed_sessions: number;
  jobs_completed: number;
  jobs_failed: number;
  tenant_id: string;
  tenant_name: string;
  tenant_type: TenantType;
  total_jobs: number;
  total_minutes: number;
  total_sessions: number;
  unique_agents: number;
}

export interface AgentMonitoring {
  agent_id: string;
  agent_identifier: string;
  cloud_provider: string | null;
  connectivity_status: ConnectivityStatus;
  current_session_start: string | null;
  deployment_metadata: any | null;
  deployment_service: string | null;
  job_count: number | null;
  last_heartbeat_at: string | null;
  lifecycle_status: LifecycleStatus;
  seconds_since_heartbeat: number | null;
  session_minutes: number | null;
  tenant_id: string;
  tenant_name: string;
  tenant_type: TenantType;
}

export interface BooleanCapability {
  default_value: boolean | null;
  supported: boolean | null;
}

export interface CatalogMetadata {
  name: string | null;
  schemas: SchemaMetadata[] | null;
}

export interface ChecksumMetrics {
  data_hashes: Record<string, string>;
  distinct_counts: Record<string, number>;
  error_message: string;
  level: ChecksumValidationLevel;
  null_counts: Record<string, number>;
  row_count: number;
}

export interface ChecksumValidationResult {
  destination_row_count: number;
  error_message: string;
  level: ChecksumValidationLevel;
  source_row_count: number;
  valid: boolean;
}

export interface ConnectorCapabilitiesConfig {
  checksum_validation_level: FieldCapability | null;
  destination_table_handling: FieldCapability | null;
  identifier_case_sensitive: BooleanCapability | null;
  ingestion_mode: FieldCapability | null;
  load_mode: FieldCapability | null;
  load_optimization_mode: FieldCapability | null;
  namespace_rules: FieldCapability | null;
  perform_hard_deletes: BooleanCapability | null;
  propagate_empty_table_schema: BooleanCapability | null;
  requires_explicit_load_step: BooleanCapability | null;
  requires_staging: BooleanCapability | null;
  schema_evolution_mode: FieldCapability | null;
  supports_async: BooleanCapability | null;
  supports_catalogs: BooleanCapability | null;
  supports_cdc: BooleanCapability | null;
  supports_checkpointing: BooleanCapability | null;
  supports_parallelization: BooleanCapability | null;
  supports_rate_limit: BooleanCapability | null;
  supports_row_hash_merge: BooleanCapability | null;
  supports_schemas: BooleanCapability | null;
  supports_staging: BooleanCapability | null;
  trigger_auto_re_sync_on_new_column: BooleanCapability | null;
  trigger_auto_re_sync_on_new_table: BooleanCapability | null;
  trigger_auto_re_sync_on_schema_change: BooleanCapability | null;
}

export interface Datasource {
  api_name: string;
  configs: Record<string, any>;
  connector_version_id: string;
  created_at: any;
  created_by: string;
  description: string | null;
  id: string;
  name: string;
  state: State;
  updated_at: any;
  updated_by: string;
  workspace_id: string;
}

export interface DatasourceInitResponse {
  datasource_metadata: CatalogMetadata[];
  datasource_product_name: string;
  datasource_product_version: string;
  datasource_properties: Record<string, string>;
  default_catalog: string;
  default_schema: string;
}

export interface DatasourceSchemaRefreshHistory {
  catalog_name: string;
  changed_objects: number;
  created_at: string;
  created_by: string;
  datasource_id: string;
  deleted: boolean;
  deleted_objects: number;
  fully_qualified_schema_name: string;
  id: string;
  job_id: string;
  new_objects: number;
  refresh_status: JobStatus;
  refresh_status_message: string;
  refresh_timestamp: string;
  schema_name: string;
  total_objects: number;
  updated_at: string;
  updated_by: string;
}

export interface DatasourceWithConnector {
  api_name: string;
  configs: Record<string, any>;
  connector_artifact_id: string;
  connector_capabilities: ConnectorCapabilities[];
  connector_description: string | null;
  connector_group_id: string;
  connector_icon: string;
  connector_id: string;
  connector_java_class: string;
  connector_name: string;
  connector_release_stage: ReleaseStage;
  connector_type: string;
  connector_vendor: string;
  connector_version: string;
  connector_version_capabilities_config: ConnectorCapabilitiesConfig | null;
  connector_version_id: string;
  connector_version_properties: any;
  created_at: any;
  created_by: string;
  description: string | null;
  force_refresh: boolean | null;
  id: string;
  java_class: string;
  name: string;
  state: State;
  type: string;
  updated_at: any;
  updated_by: string;
  version: string;
  workspace_id: string;
}

export interface DatasourcesWithAccess {
  api_name: string;
  configs: Record<string, any>;
  connector_artifact_id: string;
  connector_capabilities: Record<string, any>;
  connector_description: string | null;
  connector_group_id: string;
  connector_icon: string;
  connector_id: string;
  connector_java_class: string;
  connector_name: string;
  connector_release_stage: ReleaseStage;
  connector_type: ConnectorType;
  connector_vendor: string;
  connector_version: string;
  connector_version_capabilities_config: ConnectorCapabilitiesConfig | null;
  connector_version_id: string;
  connector_version_properties: Record<string, any>;
  created_at: string;
  created_by: string;
  created_by_name: string;
  description: string | null;
  destination_pipeline_count: number;
  id: string;
  name: string;
  source_pipeline_count: number;
  state: State;
  total_pipeline_count: number;
  updated_at: string;
  updated_by: string;
  updated_by_name: string;
  user_access_level: AccessLevel | null;
  workspace_id: string;
}

export interface ExecutionResult {
  message: string;
  status_code: string;
  success: boolean;
}

export interface FieldCapability {
  default_value: string | null;
  enabled: boolean | null;
  supported_values: string[] | null;
}

export interface FieldMetadata {
  activation_lookup: Record<string, any>[] | null;
  activation_target_field: string[] | null;
  auto_generated: boolean | null;
  can_truncate_value: boolean | null;
  canonical_type: CanonicalType | null;
  computed: boolean | null;
  createable: boolean | null;
  cursor_capable: boolean | null;
  cursor_field: boolean | null;
  custom_attributes: Record<string, any> | null;
  default_value: string | null;
  defaulted_on_create: boolean | null;
  deleted: boolean | null;
  deleted_at: string | null;
  deletion_indicator: boolean | null;
  description: string | null;
  external_id: boolean | null;
  filterable: boolean | null;
  format: string | null;
  formatted_name: string | null;
  formula_field: boolean | null;
  fully_qualified_name: string | null;
  label: string | null;
  multi_value: boolean | null;
  multi_value_separator: string | null;
  name: string;
  nillable: boolean | null;
  original_data_type: string | null;
  original_name: string | null;
  precision: number | null;
  primary_key: boolean | null;
  primary_key_capable: boolean | null;
  primary_key_ordinal: number | null;
  read_only: boolean | null;
  scale: number | null;
  select_expression: string | null;
  selected: boolean | null;
  skipped: boolean;
  skipped_reason: MetadataSkipReason | null;
  source_cursor_field: boolean | null;
  source_primary_key: boolean | null;
  system_field: boolean | null;
  table_name: string | null;
  type: any | null;
  unique: boolean | null;
  updateable: boolean | null;
}

export interface GetPipelineMetadataMappingRpcResult {
  catalog_updated_at: string;
  catalog_version: number;
  datasource_id: string;
  fully_qualified_source_object_name: string;
  mapping_id: string | null;
  merged_metadata: ObjectMetadata | null;
  pipeline_id: string;
  selected_at: string | null;
  selected_source_metadata: ObjectMetadata | null;
  selection_origin: SelectionOrigin | null;
  source_catalog_id: string;
  source_metadata: ObjectMetadata;
}

export interface IncrementalField {
  field_name: string;
  max_value_seen: string;
  record_count: number;
  value: string;
}

export interface Job {
  agent_id: string | null;
  base_path: string | null;
  created_at: any;
  created_by: string;
  ended_at: string | null;
  error_path: string | null;
  execution_duration_ms: number | null;
  id: string;
  job_command: string | null;
  job_directory: string | null;
  job_parameters: any | null;
  job_response: any | null;
  job_status: JobStatus;
  job_type: JobType;
  log_level: string;
  log_path: string | null;
  metadata: Record<string, any> | null;
  name: string;
  orchestration_run_id: string | null;
  orchestration_run_step_id: string | null;
  reference_id: string | null;
  reference_type: EntityType;
  result_path: string | null;
  schedule_execution_id: string | null;
  started_at: string | null;
  state: State;
  status_message: string | null;
  tenant_id: string;
  updated_at: any;
  updated_by: string;
  workspace_id: string;
}

export interface JobDetailV2 {
  created_at: any;
  created_by: string;
  fully_qualified_source_object_name: string;
  id: string;
  ingestion_metrics: JobStageMetrics;
  ingestion_status: JobStatus;
  ingestion_status_message: string;
  job_id: string;
  job_parameters: any;
  job_status: JobStatus;
  loading_metrics: JobStageMetrics;
  loading_status: JobStatus;
  loading_status_message: string;
  metadata_mapping_id: string;
  parent_dependencies_met: boolean;
  paths: JobPaths;
  staging_metrics: JobStageMetrics;
  staging_status: JobStatus;
  staging_status_message: string;
  status_message: string;
  updated_at: any;
  updated_by: string;
}

export interface JobDetailsStageStatusSummary {
  job_count: number;
  job_status: JobStatus;
  stage: string;
  stage_status: JobStatus;
}

export interface JobExecutionResult {
  execution_time_ms: number;
  job_id: string;
  message: string;
  module_result: ExecutionResult;
  status: JobStatus;
  status_message: string;
  success: boolean;
}

export interface JobPaths {
  base_path: string;
  context_path: string;
  data_path: string;
  error_path: string;
  log_path: string;
  stage_prefix: string;
  success_path: string;
}

export interface JobPosition {
  created_at: any;
  created_by: string;
  end_values: any;
  full_resync: boolean;
  fully_qualified_source_object_name: string;
  id: string;
  initial_sync: boolean;
  job_details_id: string;
  last_job_status: JobStatus;
  metadata_mapping_id: string;
  pipeline_id: string;
  reset_target: boolean;
  start_values: any;
  updated_at: any;
  updated_by: string;
}

export interface JobProgress {
  count_unit: string | null;
  current_count: number | null;
  current_step: number | null;
  error: string | null;
  job_metadata: Record<string, any> | null;
  job_type: string;
  overall_duration_ms: number | null;
  overall_end_time: number | null;
  overall_start_time: number | null;
  overall_status: JobStatus;
  progress_percentage: number | null;
  progress_type: ProgressType;
  steps: JobStep[] | null;
  total_count: number | null;
  total_steps: number | null;
  warnings: string[] | null;
}

export interface JobProgressBuilder {
  jobMetadata: any;
}

export interface JobStageMetrics {
  checksum_metrics: any;
  error_row_count: number;
  execution_end_time: number;
  execution_start_time: number;
  input_file_count: number;
  input_file_size: number;
  input_row_count: number;
  number_of_rows_deleted: number;
  number_of_rows_inserted: number;
  number_of_rows_updated: number;
  operation_cost: number;
  output_file_count: number;
  output_file_size: number;
  output_row_count: number;
}

export interface JobStep {
  step_description: string;
  step_duration_ms: number | null;
  step_end_time: number | null;
  step_error: string | null;
  step_metadata: Record<string, any> | null;
  step_name: string;
  step_start_time: number | null;
  step_status: JobStatus;
}

export interface MappingProcessing {
  catalog_versions_updated: number;
  deleted_objects_retained: number;
  mappings_field_evolved: number;
  mappings_marked_skipped: number;
  mappings_unmarked_skipped: number;
  new_mappings_created: number;
}

export interface ObjectMetadata {
  activation_behaviour: Record<string, any> | null;
  activation_target: Record<string, any> | null;
  catalog: string | null;
  child_settings: any | null;
  cursor_field_locked: boolean | null;
  custom_attributes: Record<string, any> | null;
  deleted: boolean | null;
  deleted_at: string | null;
  description: string | null;
  field_selection_mode: string | null;
  fields: FieldMetadata[] | null;
  formatted_catalog: string | null;
  formatted_fully_qualified_name: string | null;
  formatted_fully_qualified_schema_name: string | null;
  formatted_name: string | null;
  formatted_schema: string | null;
  fully_qualified_name: string;
  identity_strategy: IdentityStrategy | null;
  incremental_strategy: IncrementalStrategy | null;
  name: string;
  normalized_fully_qualified_name: string | null;
  object_type: ObjectType | null;
  original_catalog: string | null;
  original_name: string | null;
  original_schema: string | null;
  override_load_mode: LoadMode | null;
  parent_controlled_incremental: boolean | null;
  parent_table_name: string | null;
  primary_key_locked: boolean | null;
  schema: string | null;
  selected: boolean | null;
  selected_field_count: number;
  selected_merge_keys: string[] | null;
  skipped: boolean;
  skipped_reason: MetadataSkipReason | null;
  source_cursor_fields: string[];
  source_primary_keys: string[];
  total_field_count: number;
  type: string;
}

export interface Orchestration {
  api_name: string;
  created_at: string;
  created_by: string;
  description: string | null;
  id: string;
  name: string;
  state: State;
  updated_at: string;
  updated_by: string;
  workspace_id: string;
}

export interface OrchestrationRun {
  completed_at: string | null;
  created_at: string;
  created_by: string;
  entries_completed: number;
  entries_failed: number;
  entries_total: number;
  error_message: string | null;
  id: string;
  orchestration_id: string;
  schedule_execution_id: string | null;
  status: JobStatus;
  triggered_at: string;
  updated_at: string;
  updated_by: string;
  workspace_id: string;
}

export interface OrchestrationRunStep {
  completed_at: string | null;
  continue_on_error: boolean;
  created_at: string;
  created_by: string;
  depends_on_definition_ids: string[] | null;
  entry_type: string;
  error_message: string | null;
  id: string;
  job_id: string | null;
  orchestration_run_id: string;
  orchestration_step_id: string | null;
  position: number;
  reference_id: string;
  reference_name: string | null;
  started_at: string | null;
  status: JobStatus;
  updated_at: string;
  updated_by: string;
}

export interface OrchestrationStep {
  config: Record<string, any>;
  continue_on_error: boolean;
  created_at: string;
  created_by: string;
  depends_on: string[] | null;
  entry_type: string;
  id: string;
  orchestration_id: string;
  position: number;
  reference_id: string;
  reference_name: string | null;
  retry_count: number;
  retry_delay_seconds: number;
  state: State;
  timeout_seconds: number | null;
  updated_at: string;
  updated_by: string;
}

export interface OrchestrationsWithAccess {
  api_name: string;
  created_at: string;
  created_by: string;
  created_by_name: string;
  description: string | null;
  id: string;
  last_run_completed_at: string | null;
  last_run_created_at: string | null;
  last_run_duration_seconds: number | null;
  last_run_entries_completed: number | null;
  last_run_entries_failed: number | null;
  last_run_entries_total: number | null;
  last_run_error: string | null;
  last_run_id: string | null;
  last_run_status: JobStatus | null;
  last_run_success_rate: number | null;
  last_run_triggered_at: string | null;
  last_run_updated_at: string | null;
  name: string;
  state: State;
  step_count: number;
  updated_at: string;
  updated_by: string;
  updated_by_name: string;
  user_access_level: AccessLevel | null;
  workspace_id: string;
}

export interface Pipeline {
  api_name: string;
  configs: any;
  created_at: any;
  created_by: string;
  description: string | null;
  destination_datasource_id: string;
  id: string;
  last_manual_select_at: string | null;
  name: string;
  project_id: string;
  source_datasource_id: string;
  state: State;
  updated_at: any;
  updated_by: string;
  version_id: string;
}

export interface PipelineConfig {
  buffer_size_bytes: number | null;
  checksum_threshold_percent: number | null;
  checksum_validation_level: ChecksumValidationLevel | null;
  chunk_size_mb: number | null;
  destination_config: DatasourceWithConnector | null;
  destination_table_handling: DestinationTableHandling;
  error_handling: ErrorHandling;
  file_format: any | null;
  force_schema_refresh: boolean;
  full_resync_frequency: FullResyncFrequency | null;
  full_sync_frequency: FullSyncFrequency | null;
  ingestion_mode: IngestionMode;
  ingestion_parallelism: number | null;
  is_custom_prefix: boolean;
  load_mode: LoadMode;
  load_optimization_mode: LoadOptimizationMode | null;
  loading_parallelism: number | null;
  namespace_rules: any;
  perform_hard_deletes: boolean;
  pipeline_prefix: string;
  pipeline_type: PipelineType;
  pipeline_version_config: PipelineVersionConfig | null;
  propagate_empty_table_schema: boolean;
  schema_evolution_mode: SchemaEvolutionMode;
  source_config: DatasourceWithConnector | null;
  staging_parallelism: number | null;
  trigger_auto_re_sync_on_new_column: boolean;
  trigger_auto_re_sync_on_new_table: boolean;
  trigger_auto_re_sync_on_schema_change: boolean;
  trigger_auto_re_sync_on_schema_failure: boolean;
}

export interface PipelineJobParameters {
  child_settings: any;
  custom_state: Record<string, any>;
  effective_ingestion_mode: IngestionMode;
  effective_load_mode: LoadMode;
  full_resync: boolean;
  full_resync_due: boolean;
  full_resync_frequency: FullResyncFrequency;
  historical_due: boolean;
  historical_frequency: FullSyncFrequency;
  incremental_fields_end_values: IncrementalField[];
  incremental_fields_start_values: IncrementalField[];
  ingestion_mode: IngestionMode;
  initial_sync: boolean;
  is_incremental_capable: boolean;
  is_merge_capable: boolean;
  load_mode: LoadMode;
  load_mode_override_reason: string;
  parent_object_name: string;
  parent_row_count: number;
  requested_ingestion_mode: IngestionMode;
  requested_load_mode: LoadMode;
  requires_parent_data: boolean;
  reset_target: boolean;
  run_reason: string;
  selected_source_metadata: ObjectMetadata;
  source_catalog_id: string;
  supa_object_type: ObjectType;
}

export interface PipelineMappingProcessorRpcResult {
  created_count: number;
  error: string;
  error_count: number;
  error_detail: string;
  mapping_processing: MappingProcessing;
  mapping_time_ms: number;
  message: string;
  skipped_count: number;
  success: boolean;
  task_generation_time_ms: number;
  total_time_ms: number;
}

export interface PipelineMetadataMapping {
  applied_at: string | null;
  created_at: string;
  created_by: string;
  destination_applied_source_catalog_id: string | null;
  destination_metadata: ObjectMetadata | null;
  id: string;
  pipeline_id: string;
  selected_at: string;
  selected_destination_metadata: ObjectMetadata | null;
  selected_source_metadata: ObjectMetadata;
  selection_origin: SelectionOrigin;
  source_catalog_id: string;
  source_fully_qualified_name: string;
  updated_at: string;
  updated_by: string;
}

export interface PipelineMetadataMappingAndSourceMetadataCatalog {
  actual_destination_metadata: ObjectMetadata | null;
  created_at: string;
  created_by: string;
  datasource_id: string;
  destination_applied_at: string | null;
  fully_qualified_source_object_name: string;
  id: string;
  last_applied_source_catalog_id: string | null;
  last_applied_source_metadata: ObjectMetadata | null;
  last_applied_source_metadata_selection: ObjectMetadata | null;
  mapped_last_applied_source_metadata: ObjectMetadata | null;
  mapped_merged_source_metadata: ObjectMetadata | null;
  merged_source_metadata: ObjectMetadata;
  parent_object_name: string | null;
  pipeline_id: string;
  selected_at: string;
  selected_source_metadata: ObjectMetadata;
  selection_origin: SelectionOrigin;
  source_catalog_id: string;
  source_metadata: ObjectMetadata;
  supa_object_type: ObjectType;
  updated_at: string;
  updated_by: string;
}

export interface PipelineSchemaRefreshHistory {
  catalog_name: string;
  created_at: string;
  created_by: string;
  fully_qualified_schema_name: string;
  id: string;
  job_id: string;
  pipeline_id: string;
  refresh_timestamp: string;
  schema_name: string;
  state: State;
  updated_at: string;
  updated_by: string;
}

export interface PipelineSourceObjectIncrementalPosition {
  created_at: string;
  created_by: string;
  custom_state: Record<string, any>;
  end_values: IncrementalField[];
  full_resync: boolean;
  fully_qualified_source_object_name: string;
  id: string;
  initial_sync: boolean;
  last_job_details_id: string;
  last_successful_sync_at: string;
  pipeline_id: string;
  pipeline_mapping_id: string;
  reset_target: boolean;
  start_values: IncrementalField[];
  updated_at: string;
  updated_by: string;
}

export interface PipelineVersion {
  configs: any;
  created_at: any;
  created_by: string;
  id: string;
  is_released: boolean;
  released_at: any;
  state: State;
  updated_at: any;
  updated_by: string;
  version: string;
}

export interface PipelineVersionConfig {
  pipeline_artifact_id: string;
  pipeline_capabilities: string[];
  pipeline_group_id: string;
  pipeline_java_class: string;
  pipeline_release_stage: string;
  pipeline_type: string;
  pipeline_vendor: string;
  pipeline_version: string;
}

export interface PipelineWithVersion {
  api_name: string;
  configs: any;
  created_at: any;
  created_by: string;
  description: string;
  destination_datasource_id: string;
  id: string;
  is_released: boolean;
  name: string;
  project_id: string;
  released_at: any;
  source_datasource_id: string;
  state: State;
  updated_at: any;
  updated_by: string;
  version_configs: any;
  version_id: string;
  version_number: string;
}

export interface PipelinesAndDatasources {
  active_schedule_count: number;
  destination_api_name: string;
  destination_connector_icon: string;
  destination_connector_id: string;
  destination_connector_name: string;
  destination_connector_release_stage: ReleaseStage;
  destination_connector_type: ConnectorType;
  destination_connector_vendor: string;
  destination_connector_version: string;
  destination_datasource_id: string;
  destination_id: string;
  destination_name: string;
  destination_state: State;
  last_job_status: JobStatus | null;
  last_sync_at: string | null;
  pipeline_api_name: string;
  pipeline_configs: Record<string, any>;
  pipeline_created_at: string;
  pipeline_created_by: string;
  pipeline_description: string | null;
  pipeline_id: string;
  pipeline_name: string;
  pipeline_state: State;
  pipeline_updated_at: string;
  pipeline_updated_by: string;
  pipeline_version_id: string;
  project_api_name: string;
  project_id: string;
  project_name: string;
  schedules: any;
  source_api_name: string;
  source_connector_icon: string;
  source_connector_id: string;
  source_connector_name: string;
  source_connector_release_stage: ReleaseStage;
  source_connector_type: ConnectorType;
  source_connector_vendor: string;
  source_connector_version: string;
  source_datasource_id: string;
  source_id: string;
  source_name: string;
  source_state: State;
  workspace_id: string;
}

export interface PipelinesWithAccess {
  active_schedule_count: number;
  created_by_name: string;
  destination_api_name: string;
  destination_connector_icon: string;
  destination_connector_id: string;
  destination_connector_name: string;
  destination_connector_release_stage: ReleaseStage;
  destination_connector_type: ConnectorType;
  destination_connector_vendor: string;
  destination_connector_version: string;
  destination_datasource_id: string;
  destination_id: string;
  destination_name: string;
  destination_state: State;
  last_job_status: JobStatus | null;
  last_sync_at: string | null;
  pipeline_api_name: string;
  pipeline_configs: Record<string, any>;
  pipeline_created_at: string;
  pipeline_created_by: string;
  pipeline_description: string | null;
  pipeline_id: string;
  pipeline_name: string;
  pipeline_state: State;
  pipeline_updated_at: string;
  pipeline_updated_by: string;
  pipeline_version_id: string;
  project_api_name: string;
  project_id: string;
  project_name: string;
  schedules: any;
  source_api_name: string;
  source_connector_icon: string;
  source_connector_id: string;
  source_connector_name: string;
  source_connector_release_stage: ReleaseStage;
  source_connector_type: ConnectorType;
  source_connector_vendor: string;
  source_connector_version: string;
  source_datasource_id: string;
  source_id: string;
  source_name: string;
  source_state: State;
  updated_by_name: string;
  user_access_level: AccessLevel | null;
  workspace_id: string;
}

export interface ProjectArtifactUploadRequest {
  category: ArtifactCategory;
  job_detail_id: string;
  job_id: string;
  job_paths: JobPaths;
  pipeline_id: string;
  tenant_id: string;
  workspace_id: string;
}

export interface ProjectsWithAccess {
  activation_count: number;
  api_name: string;
  configs: Record<string, any> | null;
  created_at: string;
  created_by: string;
  created_by_name: string;
  description: string | null;
  id: string;
  model_count: number;
  name: string;
  pipeline_count: number;
  state: State;
  test_count: number;
  type: ProjectType;
  updated_at: string;
  updated_by: string;
  updated_by_name: string;
  user_access_level: AccessLevel | null;
  warehouse_connector_name: string | null;
  warehouse_datasource_id: string;
  warehouse_icon: string | null;
  warehouse_name: string | null;
  workspace_id: string;
}

export interface SchemaMetadata {
  catalog: string | null;
  full_name: string | null;
  name: string | null;
}

export interface SchemaProcessingResult {
  error: any;
  is_deleted: boolean;
  is_end_marker: boolean;
  objects: ObjectMetadata[];
  schema: SchemaMetadata;
}

export interface SchemaRefreshResult {
  catalog_id: string;
  errors_by_schema: Record<string, any>;
  execution_time: any;
  failed_schemas: number;
  object_counts_by_schema: Record<string, number>;
  success: boolean;
  successful_schemas: number;
  total_objects: number;
  total_schemas: number;
}

export interface SourceMetadataCatalog {
  catalog_name: string | null;
  child_settings: any | null;
  created_at: string;
  created_by: string;
  datasource_id: string;
  deleted: boolean | null;
  deleted_at: string | null;
  first_discovered_at: string;
  fully_qualified_name: string;
  id: string;
  metadata_fingerprint: string;
  object_name: string;
  object_type: string;
  parent_object_name: string | null;
  schema_name: string | null;
  source_metadata: ObjectMetadata;
  supa_object_type: ObjectType;
  updated_at: string;
  updated_by: string;
  version: number;
  workspace_id: string;
}

export interface Task {
  api_name: string;
  configs: Record<string, any>;
  created_at: string;
  created_by: string;
  description: string | null;
  id: string;
  name: string;
  state: State;
  task_type: TaskType;
  updated_at: string;
  updated_by: string;
  workspace_id: string;
}

export interface TasksWithAccess {
  api_name: string;
  configs: Record<string, any>;
  created_at: string;
  created_by: string;
  created_by_name: string;
  datasource_api_name: string | null;
  datasource_connector_icon: string | null;
  datasource_connector_name: string | null;
  datasource_id: string | null;
  datasource_name: string | null;
  datasource_state: State | null;
  description: string | null;
  id: string;
  is_controller_datasource: boolean | null;
  last_job_created_at: string | null;
  last_job_id: string | null;
  last_job_status: JobStatus | null;
  last_job_status_message: string | null;
  last_job_updated_at: string | null;
  name: string;
  state: State;
  task_type: TaskType;
  updated_at: string;
  updated_by: string;
  updated_by_name: string;
  user_access_level: AccessLevel | null;
  workspace_id: string;
}

export interface Tenant {
  billing_address_country: string | null;
  billing_address_line_1: string | null;
  billing_address_line_2: string | null;
  billing_address_state: string | null;
  billing_address_zip: string | null;
  configs: any | null;
  created_at: any;
  created_by: string;
  description: string | null;
  id: string;
  name: string;
  organization_id: string | null;
  primary_contact_email: string | null;
  primary_contact_name: string | null;
  primary_contact_phone: string | null;
  state: State;
  type: TenantType | null;
  updated_at: any;
  updated_by: string;
}

export interface WorkspacesWithAccess {
  api_name: string;
  created_at: string;
  created_by: string;
  created_by_name: string;
  description: string | null;
  environment: Environment;
  id: string;
  name: string;
  state: State;
  updated_at: string;
  updated_by: string;
  updated_by_name: string;
  user_access_level: AccessLevel | null;
}

